<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\API\API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e59d0a3a-8aa1-4bbb-bef4-9ae8242e759d</UserSecretsId>
  </PropertyGroup>

</Project>
